### ISSUE TITLE
El "landing page" deberia de ser la primera pagina que ve el nuevo visitante.

### ISSUE THREAD

**Issue by pruebaer** [fimbres/sport-php#17]

**Comment by fimbres** [comment]
Como tarea deberás basarte en el mockup de la landing page para modificar la pagina que actualmente se llama `index.php` y que coincidan. (textos, imagenes y posiblemente colores)
después renombrarla a `welcome.php` y hacer un pull request de tu tarea etiquetando a este issue como `closes #17`

**Comment by verttisaurio1** [comment]
se soluciono el issue en la rama feat/welcome
